/*
 * FFN sub-block testbench (shared by all variants).
 * Loads weights + golden outputs generated by generate_ffn_data.py, runs the
 * HLS top, and compares the 312-d output against the (algorithm-faithful)
 * numpy golden. Pass criterion is relative (outputs span very different scales
 * across variants): max|err| / max|ref| < REL_TOL.
 */
#include <iostream>
#include <fstream>
#include <cmath>
#include <iomanip>
#include <string>
#include "../include/ffn_model.hpp"

#ifndef NUM_TEST_SAMPLES
#define NUM_TEST_SAMPLES 16
#endif
#define REL_TOL 0.02

static float fc1_w_f[FC1_WEIGHT_AXI_BLOCKS * AXI_BLOCK_SIZE];
static float fc2_w_f[FC2_WEIGHT_BLOCKS * AXI_BLOCK_SIZE];
static float in_f[NUM_TEST_SAMPLES * INPUT_DIM];
static float ref_f[NUM_TEST_SAMPLES * OUTPUT_DIM];

static axi_block_t fc1_axi[FC1_WEIGHT_AXI_BLOCKS];
static axi_block_t fc2_axi[FC2_WEIGHT_BLOCKS];

static bool load_values(const std::string& fn, float* d, int n) {
    std::ifstream f(fn);
    if (!f.is_open()) { std::cerr << "ERROR: cannot open " << fn << "\n"; return false; }
    for (int i = 0; i < n; i++)
        if (!(f >> d[i])) { std::cerr << "ERROR: short read " << fn << " (" << i << "/" << n << ")\n"; return false; }
    return true;
}

static std::string find_data_dir() {
    const std::string cand[] = {"../../data", "../../../data", "../../../../data",
                                "../../../../../data", "data", "../data"};
    for (const auto& d : cand) {
        std::ifstream f(d + "/fc1_weights.txt");
        if (f.is_open()) { std::cout << "[TB] data dir: " << d << "\n"; return d; }
    }
    return "../../data";
}

int main() {
    std::string dd = find_data_dir();
    std::cout << "FFN testbench  IN=" << INPUT_DIM << " HID=" << HIDDEN_DIM
              << " OUT=" << OUTPUT_DIM << "  samples=" << NUM_TEST_SAMPLES << "\n";

    if (!load_values(dd + "/fc1_weights.txt", fc1_w_f, FC1_WEIGHT_AXI_BLOCKS * AXI_BLOCK_SIZE)) return 1;
    if (!load_values(dd + "/fc2_weights.txt", fc2_w_f, OUTPUT_DIM * HIDDEN_DIM)) return 1;
    if (!load_values(dd + "/test_input.txt", in_f, NUM_TEST_SAMPLES * INPUT_DIM)) return 1;
    if (!load_values(dd + "/test_output_ref.txt", ref_f, NUM_TEST_SAMPLES * OUTPUT_DIM)) return 1;

    for (unsigned int b = 0; b < FC1_WEIGHT_AXI_BLOCKS; b++)
        for (unsigned int i = 0; i < AXI_BLOCK_SIZE; i++)
            fc1_axi[b][i] = data_t(fc1_w_f[b * AXI_BLOCK_SIZE + i]);
    // fc2 file holds exactly OUTPUT*HIDDEN values (HIDDEN divisible by 8)
    for (unsigned int idx = 0; idx < OUTPUT_DIM * HIDDEN_DIM; idx++)
        fc2_axi[idx / AXI_BLOCK_SIZE][idx % AXI_BLOCK_SIZE] = data_t(fc2_w_f[idx]);

    float g_max_rel = 0.0f, g_min_cos = 1.0f;
    int pass = 0;
    for (int s = 0; s < NUM_TEST_SAMPLES; s++) {
        axi_block_t in_axi[INPUT_BLOCKS];
        for (unsigned int idx = 0; idx < INPUT_BLOCKS * AXI_BLOCK_SIZE; idx++) {
            float v = (idx < INPUT_DIM) ? in_f[s * INPUT_DIM + idx] : 0.0f;
            in_axi[idx / AXI_BLOCK_SIZE][idx % AXI_BLOCK_SIZE] = data_t(v);
        }

        wide_t out[OUTPUT_DIM];
        ffn_top(out, in_axi, fc1_axi, fc2_axi);

        float max_err = 0.0f, max_ref = 1e-9f, dot = 0, nh = 0, nr = 0;
        for (int o = 0; o < (int)OUTPUT_DIM; o++) {
            float hv = (float)out[o];
            float rv = ref_f[s * OUTPUT_DIM + o];
            max_err = std::max(max_err, std::fabs(hv - rv));
            max_ref = std::max(max_ref, std::fabs(rv));
            dot += hv * rv; nh += hv * hv; nr += rv * rv;
        }
        float rel = max_err / max_ref;
        float cos = dot / (std::sqrt(nh) * std::sqrt(nr) + 1e-30f);
        g_max_rel = std::max(g_max_rel, rel);
        g_min_cos = std::min(g_min_cos, cos);
        if (rel < REL_TOL) pass++;
        std::cout << std::fixed << std::setprecision(6)
                  << "  sample " << s << ": max_abs_err=" << max_err
                  << " max|ref|=" << max_ref << " rel=" << rel
                  << " cos=" << cos << (rel < REL_TOL ? "  OK" : "  WARN") << "\n";
    }

    std::cout << "----\n  passed " << pass << "/" << NUM_TEST_SAMPLES
              << "  worst_rel=" << g_max_rel << "  worst_cos=" << g_min_cos << "\n";
    std::cout << (pass == NUM_TEST_SAMPLES ? "RESULT: ALL PASSED\n" : "RESULT: SOME EXCEEDED TOL\n");
    return (pass == NUM_TEST_SAMPLES) ? 0 : 1;
}
