"""
Render paper TABLE XII: SST-2 accuracy, latency, and FPGA resource utilization
for full 4-layer FFN substitution in TinyBERT4.

Reads two committed CSVs and writes Markdown + LaTeX. No network, no GPU, no
training -- this is the artifact's smoke test.

  results/table_xii_acc.csv   the accuracy row, RECOMPUTED from the shipped
                              weights by eval_release.py
  results/table_xii_hls.csv   the latency/DSP/BRAM/FF/LUT rows, TRANSCRIBED from
                              the paper (HLS synthesis is out of scope here)

  python Transformer/make_table_xii.py
  python Transformer/make_table_xii.py --no-hls    # accuracy row only
"""

import argparse
import csv
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

# Column order as printed in the paper.
COLUMNS = ["teacher", "gelu_h600", "bern_h600", "gelu_h312", "bern_h312"]
COL_LABELS = {
    "teacher": "TinyBERT4",
    "gelu_h600": "h=600 GeLU", "bern_h600": "h=600 Bern",
    "gelu_h312": "h=312 GeLU", "bern_h312": "h=312 Bern",
}
METRIC_LABELS = {
    "latency": "Lat. (cycles)", "dsp": "DSP", "bram": "BRAM",
    "ff": "FF", "lut": "LUT",
}
SCOPE_LABELS = {"ffn": "FFN", "full": "Full"}


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Render paper TABLE XII")
    p.add_argument("--acc-csv", default=os.path.join(_HERE, "results", "table_xii_acc.csv"))
    p.add_argument("--hls-csv", default=os.path.join(_HERE, "results", "table_xii_hls.csv"))
    p.add_argument("--out-dir", default=os.path.join(_HERE, "results"))
    p.add_argument("--no-hls", action="store_true",
                   help="render only the recomputed accuracy row")
    return p.parse_args()


def read_acc(path: str) -> dict:
    if not os.path.exists(path):
        raise SystemExit(
            f"missing {path}\nGenerate it first:  python Transformer/eval_release.py")
    with open(path, newline="") as f:
        rows = list(csv.DictReader(f))
    acc = {r["variant"]: float(r["acc"]) for r in rows}
    missing = [c for c in COLUMNS if c not in acc]
    if missing:
        raise SystemExit(
            f"{path} is missing variants {missing}\n"
            "Re-run `python Transformer/eval_release.py` without --variants/--no-teacher.")
    return acc


def read_hls(path: str) -> list:
    """Rows of (scope, metric, {variant: (value, pct_or_None)}), file order kept."""
    if not os.path.exists(path):
        raise SystemExit(f"missing {path}")
    with open(path, newline="") as f:
        lines = [ln for ln in f if not ln.lstrip().startswith("#")]
    out = []
    for r in csv.DictReader(lines):
        vals = {"teacher": (int(r["teacher"]), None)}
        for c in COLUMNS[1:]:
            vals[c] = (int(r[c]), float(r[c + "_pct"]))
        out.append((r["scope"], r["metric"], vals))
    return out


def fmt_pct(pct: float) -> str:
    """Signed percentage the way the paper writes it (down-arrow = reduction)."""
    if pct == 0.0:
        return "0.0%"
    return f"{'↓' if pct < 0 else '↑'}{abs(pct):.1f}%"


def fmt_pct_tex(pct: float) -> str:
    if pct == 0.0:
        return r"0.0\%"
    arrow = r"\downarrow" if pct < 0 else r"\uparrow"
    return rf"${arrow}${abs(pct):.1f}\%"


def render_markdown(acc: dict, hls: list) -> str:
    head = ["Scope", "Metric"] + [COL_LABELS[c] for c in COLUMNS]
    lines = [
        "# TABLE XII -- SST-2 accuracy, latency, and FPGA resource utilization",
        "",
        "Full 4-layer FFN substitution in TinyBERT4. FFN: FFN sublayers only;",
        "Full: complete encoder. Resource changes are relative to TinyBERT4.",
        "",
        "| " + " | ".join(head) + " |",
        "|" + "---|" * len(head),
    ]
    lines.append("| SST-2 | Acc. (%) | "
                 + " | ".join(f"{acc[c] * 100:.2f}" for c in COLUMNS) + " |")
    for scope, metric, vals in hls:
        cells = []
        for c in COLUMNS:
            v, pct = vals[c]
            cells.append(f"{v:,}" if pct is None else f"{v:,} ({fmt_pct(pct)})")
        lines.append(f"| {SCOPE_LABELS[scope]} | {METRIC_LABELS[metric]} | "
                     + " | ".join(cells) + " |")
    lines += [
        "",
        "The **SST-2 Acc.** row is recomputed from the shipped weights by",
        "`eval_release.py`. The latency and resource rows are **transcribed from the",
        "paper**. Matching HLS projects can be regenerated and synthesized with",
        "`generate_and_synthesize_table_xii.py`.",
        "",
    ]
    return "\n".join(lines)


def render_latex(acc: dict, hls: list) -> str:
    lines = [
        r"% TABLE XII -- generated by Transformer/make_table_xii.py",
        r"% Accuracy row recomputed from the shipped weights (eval_release.py).",
        r"% Latency/resource rows transcribed from the paper (HLS out of scope).",
        r"\begin{tabular}{ll" + "r" * len(COLUMNS) + "}",
        r"\toprule",
        r"Scope & Metric & " + " & ".join(COL_LABELS[c] for c in COLUMNS) + r" \\",
        r"\midrule",
        r"SST-2 & Acc. (\%) & "
        + " & ".join(f"{acc[c] * 100:.2f}" for c in COLUMNS) + r" \\",
    ]
    prev_scope = None
    for scope, metric, vals in hls:
        if scope != prev_scope:
            lines.append(r"\midrule")
            prev_scope = scope
        cells = []
        for c in COLUMNS:
            v, pct = vals[c]
            cells.append(f"{v:,}" if pct is None
                         else f"{v:,} ({fmt_pct_tex(pct)})")
        lines.append(f"{SCOPE_LABELS[scope]} & {METRIC_LABELS[metric]} & "
                     + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def main() -> None:
    args = parse_args()
    acc = read_acc(args.acc_csv)
    hls = [] if args.no_hls else read_hls(args.hls_csv)

    md = render_markdown(acc, hls)
    print(md)

    os.makedirs(args.out_dir, exist_ok=True)
    md_path = os.path.join(args.out_dir, "RESULTS_table_xii.md")
    tex_path = os.path.join(args.out_dir, "table_xii.tex")
    with open(md_path, "w") as f:
        f.write(md)
    with open(tex_path, "w") as f:
        f.write(render_latex(acc, hls))
    print(f"Wrote {md_path}")
    print(f"Wrote {tex_path}")


if __name__ == "__main__":
    main()
